### ISSUE TITLE
Cannot Send Coins to Exchange From Stellar Wallet. . .

### ISSUE THREAD

**Issue by silverngold** [stellarchat/desktop-client#274]
Hello there,
 
I am trying to send a deposit from my wallet on my linux os to Binance.

I am using Stellar Desktop Linux 64-v3.6 

I have tried numerous times to send from Stellar Wallet to deposit into Binance and had their support involved until they finally asked me to contact support for Stellar Wallet.

Here's what kept happening:    ' Transaction submission failed. Server responded: 400 Bad Request '

Here were the steps I took:
 
I input the 'Memo' numbers from the deposit page on Binance to my wallet on my computer into the 'Memo' field. '1055295310'
I then input the 'XLM Deposit Address' from the page on Binance to my wallet on my computer into the 'Recipient' field. 'GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A'
I then input the amount of 'XLM' into the 'Amount' field into my wallet on my computer. '3804'
I then choose XLM on my wallet to ensure that I can send to Binance.
 
Once all three fields have been filled out and xlm has been chosen - I click the 'send' button and receive these messages:
 

    ' Transaction submission failed. Server responded: 400 Bad Request '

    ' The account can accept XLM '

 
Please help.
 
 
Sincerely,
 
Vincent Glenn: Tankersley

**Comment by Akuukis** [comment]
The next version of Foxlet 5.0.0 is not released yet. A more thoughtful process is in the makings now. Recently FIC Network has released a test built of it, as they also use this wallet for their network.

I believe this is already fixed in test build - here are all  `v5.0.0-alpha.d4c43` links for [Windows exe](https://s3.amazonaws.com/ficnetwork-public/foxlet-5.0.0-alpha.d4c43.exe), [Linux's deb](https://s3.amazonaws.com/ficnetwork-public/foxlet-5.0.0-alpha.d4c43.deb) and [Mac's zip](https://s3.amazonaws.com/ficnetwork-public/foxlet-5.0.0-alpha.d4c43.zip). Please try it out and let us know if that's already fixed.

**Comment by silverngold** [comment]
How do I transfer coins from v3.6 to Foxlet v5.0?

**Comment by Akuukis** [comment]
Very simple. First, backup your walletfile just in case, i.e. copy paste somewhere else. Second, open the walletfile with the new Foxlet version, that's all.

**Comment by silverngold** [comment]
Hi There Akuukis! 

I am still having issues in sending the lumens - What's happening now is
that after I hit 'send' it just spirals as if in a que' that takes
forever and Binance still has not received the coins. 

Thank you very much for Foxlet as that did work just like you said and
has replaced v.3.6.  Sooo, at least it's not showing a '400' Bad Request
anymore and that's a step in the right direction. 

Sincerely, 

Vincent Glenn: Tankersley 

On 2018-07-24 5:05 am, Akuukis wrote:

> Very simple. First, backup your walletfile just in case, i.e. copy paste somewhere else. Second, open the walletfile with the new Foxlet version, that's all. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/stellarchat/desktop-client/issues/274#issuecomment-407335856
[2]

**Comment by silverngold** [comment]
Still unable to 'send' out coins to Binance even though using Linux
Foxlet 5.0 on linux OS. 

No longer showing 'bad request' but hangs up in que as though sending
forever. 

On 2018-07-24 5:05 am, Akuukis wrote:

> Very simple. First, backup your walletfile just in case, i.e. copy paste somewhere else. Second, open the walletfile with the new Foxlet version, that's all. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/stellarchat/desktop-client/issues/274#issuecomment-407335856
[2]

**Comment by Akuukis** [comment]
@silverngold Are you using the "Send" tab or "service" tab? The "send" is working for me, but "service" most likely is still broken, please see #264 .

**Comment by silverngold** [comment]
I've been using only the 'Send' Tab.  Haven't even fooled with the
'Service' Tab. 

On 2018-07-25 12:59 pm, Akuukis wrote:

> @silverngold [1] Are you using the "Send" tab or "service" tab? The "send" is working for me, but "service" most likely is still broken, please see #264 [2] . 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].
 

Links:
------
[1] https://github.com/silverngold
[2] https://github.com/stellarchat/desktop-client/pull/264
[3]
https://github.com/stellarchat/desktop-client/issues/274#issuecomment-407824497
[4]

**Comment by silverngold** [comment]
I also tried sending the coins over again - problem continues to be the
same. 

I log into Foxlet.  Click the 'Send' tab. 

I log into Binance click on the funds button - pick XLM - copy the memo
id - paste the memo into the memo field in the send tab of Foxlet - copy
the address - paste the address in the send tab of Foxlet - I then input
the desired amount of lumens to send - I then click the green 'Choose
XLM' button - (Note: I make certain that the memo field shows that
'text' has been chosen before sending) - I then click send in which the
blue circle spins and says, 'Loading...' and it stays that way. 

It should literally take just a few seconds for the deposit to go
through. 

Perhaps it is a server issue?  At the very start I've been using Horizon
Stellar.org 

Should I try a different wallet and if so, how do I transfer the coins? 

Sincerely, 

Vincent Glenn: Tankersley 

On 2018-07-25 12:59 pm, Akuukis wrote:

> @silverngold [1] Are you using the "Send" tab or "service" tab? The "send" is working for me, but "service" most likely is still broken, please see #264 [2] . 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].
 

Links:
------
[1] https://github.com/silverngold
[2] https://github.com/stellarchat/desktop-client/pull/264
[3]
https://github.com/stellarchat/desktop-client/issues/274#issuecomment-407824497
[4]

**Comment by Akuukis** [comment]
Thanks for details, that's a valid issue. I will look into it.

**Comment by silverngold** [comment]
Is there any way to get my coins out of the wallet? 

Sincerely, 

Vincent Glenn: Tankersley 

On 2018-07-26 5:24 am, Akuukis wrote:

> Thanks for details, that's a valid issue. I will look into it. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/stellarchat/desktop-client/issues/274#issuecomment-408035671
[2]

**Comment by rsoutar** [comment]
If you have a Secret Key for your wallet. You can open it with other wallets.

**Comment by silverngold** [comment]
I don't quite get how to do that?  

How would I transfer the lumens from this wallet to another wallet that may be more user friendly in sending out coins to an exchange, simply by using the secret key of this wallet?  I'm not sure how that would work.  

Could you give me a little more detail or a youtube video that explains it?  As it stands now I have coins that are locked inside my wallet that I have no way of accessing.  I can log in - it shows the balance, but when it comes to sending out coins... It's a no go. 

I even purchased a Ledger Nano S - and that didn't work either.

**Comment by IrvingBlanchard** [comment]
Hello ! I have exactly the same problem to get my XLM out of the Foxlet Wallet. He is loading forever... I also use the Foxlet 5.0 on Mac OSX. Have you found a solution since August ? Thank you !!

**Comment by liangran** [comment]
Please also try the version 4.2. It is a old version built by nwjs and it works fine.

**Comment by stellarchat** [comment]
v4.3 released, please try this version.

**Comment by BabyHubster** [comment]
I cannot sent Lumen to Exodus. Received this message, "Cannot read property 'length' of undefined"
